function diff_mfPrev=finding_VoverH_w_fzero(bit,CumMfPrev,beta,...
    alpha,k0,kLin,k1,r1,sigma1,psi1,psi2s2,mu,gamma,b1,c,ageLev,...
    k2,gam2,tau,immC,slopeC,del,ageMthMax,da,demoX,...
    bCulex,toleranceX,k0_An,k0_Cx,immCMin,larvaeDeath,PP,excessMortality)

k0Spp = assign_k0Spp(bCulex,k0_Cx,k0_An);

[~,~,~,~,mVec,~] = get_Equil_L3values(bit,beta,alpha,k0,kLin,k1,r1,...
    sigma1,psi1,psi2s2,mu,gamma,b1,c,ageLev,k2,gam2,tau,immC,slopeC,...
    immCMin,larvaeDeath,PP,del,excessMortality,k0Spp,ageMthMax,da,bCulex,...
    demoX,toleranceX);

diff_mfPrev = CumMfPrev-mfAgeprevFun(sumMf(mVec,ageMthMax,da,demoX),...
    negBinshapeFun(sumMf(mVec,ageMthMax,da,demoX),k0,kLin));

end

